server:
  port: 8081
security:
  oauth2:
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://114.215.253.76:8081/oauth/token
      userAuthorizationUri: http://114.215.253.76:8081/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://114.215.253.76:8081/user